version: '3.8'

services:
  web:
    build: .
#    command: python manage.py runserver 0.0.0.0:8000
    command: gunicorn QuizProject.wsgi:application --bind 0.0.0.0:8000
    expose:
      - 8000
    env_file:
      - ./.env
    depends_on:
      - db

  db:
    image: postgres:16
    volumes:
      - postgres_data:/var/lib/postgresql/data/
      - static_folder:/app/static
      - media_folder:/app/media
    environment:
      - POSTGRES_USER=quiz
      - POSTGRES_PASSWORD=QuizProject124
      - POSTGRES_DB=QuizDB
  nginx:
    build: ./nginx
    volumes:
      - static_folder:/app/static
    ports:
      - 80:80
    depends_on:
      - web

volumes:
  postgres_data:

  static_folder:
  media_folder: