name: QuizProject
on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master
jobs:
  first:
    name: Install requirments and execut tests
    runs-on: ubuntu-latest
    steps:
      - name: Update
        run: sudo apt update
      - name: Check out repository code
        uses: actions/checkout@v3
      - name: Install pip
        run: sudo apt install python3-pip
      - name: Install requirements
        run: pip install -r requirements.txt
      - name: Execute tests
        env:
          DJANGO_SETTINGS_MODULE: QuizProject.settings.local
          SECRET_KEY: django-insecure-%r7j$wr1#-hwcfk^m81es@uw5xz@wfd-_s&ee5p)s$vl7iv54=
        run: python manage.py test
#


